travis:
  secure:
    BINSTAR_TOKEN: VLPDoKdUujsd5It6ZNQQWTFnRvdWfAA0WKhlDlTXF8LyKlTY4wtdjcZ38ORbKNzA/b4ymzu+hVoMyw1k0oaxgPTE8lSKj1FMkq9ec/jqZJPSQ6bAHgXv0dBxn4vW0MBRPlOUSjblAoWAeMK8duUiC205Ap+z6azj7U5jHEvBtd4NUquNczlqKjtm1dpn46GmGX89b1wrHz2ZsE9YEswGRAJSdlVUVxN434EaC+sxJ/Mh0Us6dLxFXlDNv3bV1p33mpgI9vCAKlmydFFYIHu6dEmVuiSOtXNPKt5MQ+Qin4dnpc0l21bgYf8jj3pDhR8G73JsD9u2dFhB06dQqhdl3/IgJNUfeyEw15szGyaLEEfLjxr5UR+tGgL++6VR7kMCBSIgp0RC3igSs9p+3bq7frcRcVb/FzpV7iLGB1p/swH7uC0wD/6PCzz2rbVYzgGtuU3a6DgGoqDdEAG5wb04/z74ksvl4WGPjWLO00JHrTJCgSF5jjOGtHj3xWaPc+k1g+B6YrWbQpYnXp4LYd8KlN7zHIGrsIlkpw9DjV4f0xfs8pEaO2QQyyEBtEe6gEYjR7Ca06wudGq2cnRodWMt0phL8tnBKPhfe2wKpScjHA9sWJo/NE3ntdkU15yii9Q7/sCgU2Lkksb8Fc8vVkKyRREzCsL652dcF5ki9SY9mQo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
